### ISSUE TITLE
Deprecation warnings with latest doctrine bundle

### ISSUE THREAD

**Issue by lolli42** [adrenalinkin/doctrine-utc-date-time#3]
Doctrine first moans about not having 'commented: true' in the config. If that is set, it then says:

php.INFO: User Deprecated: The type "date" was marked as commented in its configuration but not in the type itself. This is deprecated and will be removed in DoctrineBundle 2.0. Please update the return value of "Linkin\Component\DoctrineUTCDateTime\DBAL\Types\UtcDateType::requiresSQLCommentHint()." {"exception":"[object] (ErrorException(code: 0): User Deprecated: The type \"date\" was marked as commented in its configuration but not in the type itself. This is deprecated and will be removed in DoctrineBundle 2.0. Please update the return value of \"Linkin\\Component\\DoctrineUTCDateTime\\DBAL\\Types\\UtcDateType::requiresSQLCommentHint().\" at .../vendor/doctrine/doctrine-bundle/ConnectionFactory.php:140)"} []

I think, the three type classes should add method requiresSQLCommentHint() and return true to get rid of that deprecation warning. After that, 'commented: true' in config can be removed again, and the deprecation is gone.

**Comment by adrenalinkin** [comment]
Hello @lolli42 !

Thanks you for information. I will check this problem as soon as possible.
If you already have solution - feel free to add PR.
